export enum ErrorCodePrefix {
  AUTH = 'AUTH',
  USER = 'USER',
  EMAIL = 'EMAIL',
  POST = 'POST',
  GENERAL = 'GENERAL',
  UNKNOWN = 'UNKNOWN',
}

export enum AuthErrorCode {
  CREDENTIALS_INVALID = '000',
  ACCESS_TOKEN_INVALID = '001',
  ACCESS_TOKEN_EXPIRES = '002',
  CSRF_TOKEN_INVALID = '003',
  CSRF_TOKEN_EXPIRES = '004',
  REFRESH_TOKEN_INVALID = '005',
  REFRESH_TOKEN_EXPIRES = '006',
  SESSION_INVALID = '007',
  SESSION_EXPIRES = '008',
}
